server {
    listen 80;
    server_name localhost;

    # Указываем корневую директорию, где Nginx будет искать файлы
    root /usr/share/nginx/html;

    # Указываем файлы, которые Nginx будет пытаться отдать по умолчанию
    index index.html index.htm;

    # Конфигурация для обработки запросов к SPA
    location / {
        # Сначала Nginx пытается найти запрошенный файл ($uri)
        # Затем пытается найти директорию ($uri/)
        # Если ни то, ни другое не найдено, он отдает index.html
        # Это позволяет React Router обрабатывать маршрутизацию
        try_files $uri $uri/ /index.html;
    }

    # Обработка ошибок
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
